name: CI - Automation Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      grep:
        description: Filter tests
        required: false
        default: ''
  schedule:
    - cron: '00 01 * * 1-5' # At 01:00 on every day-of-week from Monday through Friday

jobs:
  tests:
    name: Playwright Tests (shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy

    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]

    env:
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: |
            playwright-report
            test-results
          if-no-files-found: ignore
          retention-days: 7